import{createOpenAI}from"@ai-sdk/openai";import{generateText}from"ai";
const I="nexus-research";
const M=process.env.OPENROUTER_MODEL??"anthropic/claude-sonnet-4-5";
const log=(m)=>console.log("["+new Date().toISOString()+"]["+I+"] "+m);
const or=createOpenAI({baseURL:"https://openrouter.ai/api/v1",apiKey:process.env.OPENROUTER_API_KEY??"",headers:{"HTTP-Referer":"https://nexus-capital.ai","X-Title":I}});
const TOPICS=["best passive income online 2026 with AI automation","crypto trading bots DeFi yield that actually work","monetize AI agents for recurring revenue","highest commission affiliate niches 2026","digital products vs micro-SaaS for solo founder","AI freelance skills highest hourly rate 2026","crypto yield farming staking opportunities now","build and sell AI micro-SaaS in 30 days","dropshipping with AI automation 2026","newsletter and content income with AI tools"];
let cycle=0;const findings=[];
async function research(topic){const{text}=await generateText({model:or(M),max_tokens:700,prompt:"You are NEXUS Capital research AI for Alejandro building automated income.\n\nTOPIC: "+topic+"\n\nFormat EXACTLY:\nSCORE: [1-10]/10\nSTARTUP_COST: [$]\nTIME_TO_FIRST_$: [weeks]\nMONTHLY_POTENTIAL: [$X-$Y]\nAUTOMATION: [fully/semi/manual]\nSTEP_1: [action today]\nSTEP_2: [action this week]\nSTEP_3: [action this month]\nRISK: [one sentence]\nVERDICT: [2 honest sentences]"});const score=parseInt((text.match(/SCORE:\s*(\d+)/)||["","5"])[1])||5;return{text,score};}
async function masterReport(){const top=[...findings].sort((a,b)=>b.score-a.score);const{text}=await generateText({model:or(M),max_tokens:900,prompt:"NEXUS Capital strategist for Alejandro who wants automated online income. Research results:\n\n"+top.map((f,i)=>"[#"+(i+1)+" SCORE "+f.score+"/10] "+f.topic+"\n"+f.text.substring(0,300)).join("\n---\n")+"\n\nCreate: 1) TOP 5 ranked by automation+income+low cost 2) POWER COMBO: best 2-3 to combine 3) 30-DAY PLAN week by week 4) QUICK WIN: one thing to start TODAY for money within 7 days"});log("=".repeat(60)+"\nNEXUS MASTER REPORT:\n"+text+"\n"+"=".repeat(60));}
async function run(){cycle++;const topic=TOPICS[(cycle-1)%TOPICS.length];log("━".repeat(50));log("CYCLE #"+cycle+" | "+topic);try{const{text,score}=await research(topic);findings.push({topic,text,score});log("SCORE: "+score+"/10\n"+text);log("COVERED: "+findings.length+"/"+TOPICS.length);if(findings.length%TOPICS.length===0){log("ALL DONE - master report...");await masterReport();}}catch(e){log("ERR: "+e.message);}}
log("▶ NEXUS RESEARCH AGENT v1 | scanning "+TOPICS.length+" income opportunities every 15min");
run();setInterval(run,900000);