import{createOpenAI}from"@ai-sdk/openai";import{generateText}from"ai";
const I="nexus-research";
const M=process.env.OPENROUTER_MODEL??"anthropic/claude-sonnet-4-5";
const log=(m)=>console.log("["+new Date().toISOString()+"]["+I+"] "+m);
const or=createOpenAI({baseURL:"https://openrouter.ai/api/v1",apiKey:process.env.OPENROUTER_API_KEY??"",headers:{"HTTP-Referer":"https://nexus-capital.ai","X-Title":I}});
const TOPICS=["best passive income online 2026 with AI automation","crypto trading bots DeFi yield that actually work","monetize AI agents for recurring revenue","highest commission affiliate niches 2026","digital products vs micro-SaaS for solo founder","AI freelance skills highest hourly rate 2026","crypto yield farming staking opportunities now","build and sell AI micro-SaaS in 30 days","dropshipping with AI automation 2026","newsletter and content income with AI tools"];
let cycle=0;const findings=[];
async function getSnap(){try{const r=await fetch("https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&price_change_percentage=24h");const d=await r.json();if(!Array.isArray(d))return"unavailable";return d.map(c=>c.symbol.toUpperCase()+":$"+c.current_price+"("+c.price_change_percentage_24h?.toFixed(1)+"%)").join(", ");}catch(e){return"unavailable";}}
async function research(topic,snap){const{text}=await generateText({model:or(M),max_tokens:700,prompt:"NEXUS research AI for Alejandro.\nMarket: "+snap+"\nTOPIC: "+topic+"\nFormat:\nSCORE: [1-10]/10\nSTARTUP_COST: [$]\nTIME_TO_FIRST_$: [weeks]\nMONTHLY_POTENTIAL: [$X-$Y]\nAUTOMATION: [fully/semi/manual]\nSTEP_1: [today]\nSTEP_2: [this week]\nSTEP_3: [this month]\nRISK: [one sentence]\nVERDICT: [2 honest sentences]"});const score=parseInt((text.match(/SCORE:\s*(\d+)/)||["","5"])[1])||5;return{text,score};}
async function masterReport(){const top=[...findings].sort((a,b)=>b.score-a.score);const{text}=await generateText({model:or(M),max_tokens:900,prompt:"NEXUS strategist for Alejandro (solo founder, AI agents live on Railway).\n"+top.map((f,i)=>"[#"+(i+1)+" "+f.score+"/10] "+f.topic+"\n"+f.text.slice(0,300)).join("\n---\n")+"\n\n1. TOP 5 OPPS\n2. POWER COMBO\n3. 30-DAY SPRINT\n4. START TODAY"});log("=".repeat(60)+"\nMASTER REPORT:\n"+text+"\n"+"=".repeat(60));}
async function run(){cycle++;const topic=TOPICS[(cycle-1)%TOPICS.length];log("━".repeat(50));log("CYCLE #"+cycle+" | "+topic);try{const snap=await getSnap();const{text,score}=await research(topic,snap);findings.push({topic,text,score});log("SCORE:"+score+" "+text);log("COVERED:"+findings.length+"/"+TOPICS.length);if(findings.length%TOPICS.length===0)await masterReport();}catch(e){log("ERR:"+e.message);}}
log("NEXUS RESEARCH v2 ONLINE - array fix applied");run();setInterval(run,900000);